#!/usr/bin/env python3
"""Prepend a plain-language "what does this notebook prove" header to each notebook.

Numbers quoted in the headers come from the actual Kaggle runs of each kernel
(pulled via `kaggle kernels output`), not from estimates. Notebooks 04 and 05 are
generated by their own build scripts and already carry their headers, so they are
skipped here.
"""
import json
from pathlib import Path

ROOT = Path("/Users/kelvin/apps/public-files")
MARK = "<!-- HEADER-KLAIM -->"

HEADERS = {
"01_Metode_Mana_Paling_Akurat_EDM_vs_JSD.ipynb": """<!-- HEADER-KLAIM -->
# 01 — Metode Entropy Mana yang Paling Akurat? (EDM-Fuzzy vs JSD-Fuzzy)

| | |
|---|---|
| **Pertanyaan** | Dari 4 metode multiscale entropy, mana yang paling bagus jadi fitur untuk mendeteksi fault 4 sensor kelembaban? |
| **Jawaban** | **JSD-Fuzzy versi *rich* menang.** Pada tugas 17 kelas, akurasinya naik dari ~0,34 (JSD versi lama, 40 fitur) ke ~0,42 (versi rich, 160 fitur). Pada deteksi per-jenis-fault, JSD-Fuzzy unggul di keempat jenis fault (F1 rata-rata 0,85 vs EDM-Fuzzy). |
| **Cara membuktikan** | Data, window, skenario, dan split **identik** untuk semua metode; yang diganti hanya rumus fiturnya. ANN (MLP) + GridSearch dijalankan terpisah per metode. |
| **Isi tambahan** | RQ1–RQ5 (validasi matriks fitur, kestabilan CV, separability, 5 skenario klasifikasi, uji-t berpasangan), fitur hibrida (entropy + time-domain), biaya komputasi (waktu/CPU/memori) per metode. |
| **Catatan jujur** | Tugas 17 kelas memang sulit (akurasi ~0,5) karena kelas kombinasi saling tumpang-tindih, misalnya `drift+bias` vs `drift+spike+bias`. Ini batas tugasnya, bukan kegagalan metodenya — lihat notebook `03` yang memecahnya per tingkat kombinasi. |
| **Kaggle** | `kelvindsmn/jsd-fuzzy-ann-paper` |
| **Dibangun dari** | `archive/SUMBER_01a_Paper_Q3_RQ1_RQ5.ipynb` + `archive/SUMBER_01b_Dev_JSD_Rich.ipynb` (lewat `build_notebook.py`) |

---
""",

"02_Sensor_Digabung_Broker_Jangan_Dirata_rata.ipynb": """<!-- HEADER-KLAIM -->
# 02 — Data 4 Sensor Digabung di Broker, Tapi Jangan Dirata-rata

| | |
|---|---|
| **Pertanyaan** | Pembimbing minta data 4 sensor dikumpulkan lewat **broker** dulu sebelum masuk ANN ("jangan loncat"). Pertanyaannya: setelah dikumpulkan, apakah keempatnya boleh **dirata-rata jadi 1 sinyal**, atau harus tetap 4 jalur terpisah? |
| **Jawaban** | **Tetap 4 jalur.** Merata-ratakan 4 sensor jadi 1 justru menurunkan performa: JSD-Fuzzy F1 0,845 (4 jalur) vs 0,797 (dirata-rata); EDM-Fuzzy 0,763 vs 0,756. |
| **Kenapa begitu** | Fault `spike` dan `hardware` muncul di waktu yang berbeda-beda pada tiap sensor, jadi kalau dirata-rata, sinyalnya saling meredam (F1 spike 0,79 → 0,68; hardware 0,96 → 0,90). Fault `drift` dan `bias` yang serempak hampir tidak terpengaruh. |
| **Kesimpulan praktis** | Broker berperan sebagai **pengumpul** (menyatukan 4 aliran jadi satu tabel ter-align waktu), **bukan** peleburan sinyal. Model tetap ANN. |
| **Kaggle** | `kelvindsmn/jsd-fuzzy-broker-architecture-v2` |

---
""",

"03_Akurasi_per_Tingkat_Kombinasi_Fault.ipynb": """<!-- HEADER-KLAIM -->
# 03 — Akurasi per Tingkat Kombinasi Fault (S1–S5)

| | |
|---|---|
| **Pertanyaan** | Tugas 17 kelas sekaligus terlalu berat. Kalau dipecah menurut **berapa banyak fault yang bercampur**, seberapa akurat sebenarnya? |
| **Jawaban** | **JSD-Fuzzy menang di 4 dari 5 tingkat.** F1: S1 biner 0,798 vs 0,734 · S2 fault tunggal 0,677 vs 0,531 · S3 dua fault 0,786 vs 0,572 · S4 tiga fault 0,777 vs 0,750 · S5 empat fault 0,971 vs 0,981 (satu-satunya EDM menang). |
| **Cara membuktikan** | Split **block-split** berbasis waktu (latih = 75% awal, uji = 25% akhir per kondisi) supaya tidak bocor akibat window yang tumpang-tindih. Mengikuti skema PDF pembimbing "Skema Pengolahan Data Multisource". |
| **Catatan jujur** | `ANN-LM` di sini memakai solver `lbfgs`, karena scikit-learn tidak punya Levenberg–Marquardt sungguhan (itu ada di MATLAB `trainlm`). Ukuran window yang dipakai WIN=512; nilai N=2000/7000/10000 di PDF terlalu sedikit kalau dipakai sebagai window klasifikasi, jadi diperlakukan sebagai studi sensitivitas panjang data. |
| **Kaggle** | `kelvindsmn/jsd-fuzzy-scenario-ladder` |

---
""",

"06_ANN_vs_XGBoost.ipynb": """<!-- HEADER-KLAIM -->
# 06 — Kalau Bukan ANN, Apakah XGBoost Lebih Baik?

| | |
|---|---|
| **Pertanyaan** | Akurasi 17 kelas mentok. Apakah penyebabnya classifier-nya (ANN), atau fiturnya? |
| **Cara membuktikan** | Data, window, dan 17 skenario **identik** dengan notebook `01`. Yang diganti hanya bagian bawah: evaluasi per-skenario, penambahan fitur time-domain, dan classifier XGBoost sebagai pembanding ANN. |
| **Gunanya** | Kalau XGBoost pun mentok di angka yang mirip, berarti batasnya ada di **fitur/tugas**, bukan di ANN — ini yang memperkuat argumen bahwa tugas 17 kelas memang tumpang-tindih. |
| **Status** | Eksperimen pendamping, bukan hasil utama paper. |

---
""",

"archive/LAMA_TIDAK_VALID_Sensor_Mana_Label_Kembar.ipynb": """<!-- HEADER-KLAIM -->
# ⚠️ TIDAK VALID — JANGAN DIPAKAI UNTUK PAPER

**Notebook ini dulunya "Per-Sensor Fault Detection (Cara A)". Hasilnya tidak sah.**

| | |
|---|---|
| **Apa yang salah** | Injeksi fault-nya mengenai **keempat sensor sekaligus** pada tiap skenario. Akibatnya keempat kolom label per-sensor **identik** — prevalensi 0,882 di S1, S2, S3, dan S4, persis sama. |
| **Kenapa angkanya kelihatan bagus** | F1 0,925 yang dilaporkan hanyalah efek "selalu menebak fault" pada kolom yang 88% isinya positif. Buktinya **ROC-AUC = 0,50** untuk EDM-Fuzzy, yaitu setara menebak acak, dan keempat sensor punya angka yang sama persis. |
| **Kesimpulan** | Notebook ini **tidak pernah benar-benar membedakan sensor**. Angka apa pun dari sini tidak boleh dikutip. |
| **Penggantinya** | `04_Klasifikasi_Dulu_Baru_Sensor_Mana.ipynb` — injeksi diperbaiki jadi hanya sebagian sensor yang kena, sehingga "sensor mana" punya ground-truth sungguhan. |

---
""",

"archive/SUMBER_01a_Paper_Q3_RQ1_RQ5.ipynb": """<!-- HEADER-KLAIM -->
# 📦 ARSIP — Sumber Notebook 01 (bagian RQ1–RQ5)

Isinya sudah **digabung seluruhnya** ke `01_Metode_Mana_Paling_Akurat_EDM_vs_JSD.ipynb`
oleh `build_notebook.py`. Disimpan hanya sebagai rujukan riwayat; untuk hasil
terbaru pakai notebook `01`.

---
""",

"archive/SUMBER_01b_Dev_JSD_Rich.ipynb": """<!-- HEADER-KLAIM -->
# 📦 ARSIP — Sumber Notebook 01 (pipeline + JSD-Fuzzy *rich*)

Di sinilah perbaikan JSD-Fuzzy *rich* (`[jsd, fe, mean, std]` per skala)
pertama kali diuji. Isinya sudah **digabung seluruhnya** ke
`01_Metode_Mana_Paling_Akurat_EDM_vs_JSD.ipynb` oleh `build_notebook.py`.
Untuk hasil terbaru pakai notebook `01`.

---
""",

"archive/LAMA_EDM_v6_dengan_downsampling.ipynb": """<!-- HEADER-KLAIM -->
# 📦 ARSIP — Versi lama (EDM-Fuzzy saja, v6, memakai downsampling)

Percobaan awal sebelum JSD-Fuzzy masuk. Sudah digantikan oleh notebook `01`
yang membandingkan keempat metode dengan data & split yang sama.

---
""",

"archive/LAMA_EDM_v6_tanpa_downsampling.ipynb": """<!-- HEADER-KLAIM -->
# 📦 ARSIP — Versi lama (EDM-Fuzzy saja, v6, tanpa downsampling/windowing)

Varian dari notebook v6: fitur dihitung dari deret penuh per skenario, tanpa
downsampling maupun windowing. Sudah digantikan oleh notebook `01`.

---
""",

"archive/LAMA_Revisi2_Deteksi_per_Sensor.ipynb": """<!-- HEADER-KLAIM -->
# 📦 ARSIP — Versi lama (revisi-2, deteksi per sensor gaya awal)

Pipeline generasi awal. Sudah digantikan oleh notebook `01` (perbandingan
metode) dan `04` (identifikasi sensor yang benar).

---
""",

"archive/LAMA_Anchor_Cepat.ipynb": """<!-- HEADER-KLAIM -->
# 📦 ARSIP — Versi lama (anchor cepat untuk pembanding lintas-notebook)

Dipakai dulu untuk mengambil angka pembanding di Kaggle secara cepat. Sudah
tidak dipakai; angka pembanding sekarang ada di notebook `01`.

---
""",
}


def main():
    for rel, header in HEADERS.items():
        path = ROOT / rel
        if not path.exists():
            print("MISSING, skipped:", rel)
            continue
        nb = json.loads(path.read_text())
        cells = nb["cells"]
        # idempotent: replace an existing header cell instead of stacking a new one
        if cells and cells[0]["cell_type"] == "markdown" and MARK in "".join(cells[0]["source"]):
            cells[0]["source"] = header.splitlines(keepends=True)
            action = "replaced"
        else:
            cells.insert(0, {"cell_type": "markdown", "metadata": {},
                             "source": header.splitlines(keepends=True)})
            action = "inserted"
        path.write_text(json.dumps(nb, indent=1))
        print(f"{action:9s} header -> {rel}")


if __name__ == "__main__":
    main()
